### ISSUE TITLE
[CSGO] Server crash on client connect

### ISSUE THREAD

**Issue by Tetragromaton** [dordnung/FileNetMessages#2]
Dump
`  0: filenetmessages.ext.2.csgo.so!ClientListener::InterceptClientConnect(int, char*, unsigned int) + 0x51
     eip: 0xeae09de1  esp: 0xffebba30  ebp: 0xec66fb18  ebx: 0xeae27970
     esi: 0x00000080  edi: 0x0d514930  eax: 0x000001bd  ecx: 0x00000001
     edx: 0xf3ff7a68  efl: 0x00210206  

     eae09dd3  89 4c 24 04              mov [esp+0x4], ecx
     eae09dd7  89 04 24                 mov [esp], eax
     eae09dda  ff 52 54                 call dword [edx+0x54]
     eae09ddd  85 c0                    test eax, eax
     eae09ddf  74 cc                    jz 0xeae09dad
  >  eae09de1  8b 30                    mov esi, [eax]
     eae09de3  89 04 24                 mov [esp], eax
     eae09de6  ff 96 d0 00 00 00        call dword [esi+0xd0]
     eae09dec  8d 74 24 34              lea esi, [esp+0x34]
     eae09df0  89 34 24                 mov [esp], esi
     eae09df3  c7 44 24 08 90 95 e0 ea  mov dword [esp+0x8], 0xeae09590`

**Comment by dordnung** [comment]
Should be fixed with #3
